export const cartLocators = {
    proceedToCheckoutButton: 'button[data-role="proceed-to-checkout"]',
    multiCheckoutLink: 'a.action.multicheckout',
    itemPrice: '.cart.item .col.price .cart-price .price',
    cartSubTotal: '.cart-totals .price[data-th="Subtotal"]',
    discountAmount: '.amount[data-th="Discount"] .price',
    shippingAmount: '.amount[data-th="Shipping"] .price',
    orderTotal: '.amount[data-th="Order Total"] .price',
    editLink: '.cart.item .col.item a.product-item-photo',
    editButton: '.action.action-edit',
    itemText: 'strong.product-item-name a',
    editTittle: 'li.item.product strong',
    summaryTitle: 'div.cart-summary strong.summary.title',
    qtyInput: 'input[data-role="cart-item-qty"]',
    priceValue: 'td.col.price span.price',
    subtotalItemValue: 'td.col.subtotal span.price',
    updateCartButton: 'button.action.update',
    moreChoices: '.block.crosssell',
    addItem: 'button.action.tocart.primary',
    wishListButton: 'a.action.towishlist',
    cartButtonItem: 'a.action.tocompare',
};
