export const registrationLocators = {
    firstnameField : '#firstname',
    lastnameField : '#lastname',
    emailField : '#email_address',
    passwordField : '#password',
    confirmField : '#password-confirmation',
    strenghtText : '#password-strength-meter',
    createAccountButton: 'button[title="Create an Account"]',
    firstNameLabel: 'label:has-text("First Name")',
    lastNameLabel: 'label:has-text("Last Name")',
    emailLabel: 'label:has-text("Email")',
    passwordLabel: 'label:has-text("Password")',
    passwordStrengthLabel: '#password-strength-meter-label',
    passwordConfirmationError: '#password-confirmation-error',
    passwordError: '#password-error',
    emailError: '#email_address-error',
    lastNameError: '#lastname-error',
    firstNameError: '#firstname-error',
    
}
